version: "3.7"
services:
    fanartweb-mongo:
        image: mongo
        restart: unless-stopped
        container_name: fanartweb-mongo
        volumes:
            - mongodata:/data/db
            - ./backup:/backup
        networks:
            - default
        ports:
            - "127.0.0.1:27017:27017"
        environment:
            - NODE_ENV=production
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=fanartweb
    fanartweb-backend:
        image: acedroidx/fanartweb-backend
        restart: unless-stopped
        container_name: fanartweb-backend
        depends_on:
            - fanartweb-mongo
        networks:
            - default
        ports:
            - "127.0.0.1:2162:2162"
        environment:
            - NODE_ENV=production
            - MONGODB_PASS=fanartweb
            - MONGODB_IP=fanartweb-mongo
            - BILI_COOKIE=
    fanartweb-frontend:
        image: acedroidx/fanartweb-frontend
        restart: unless-stopped
        container_name: fanartweb-frontend
        networks:
            - default
        environment:
            - NODE_ENV=production
            - BASE_API_URL=
    caddy:
        image: caddy
        restart: unless-stopped
        container_name: caddy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/caddydata:/data
            - ./data/caddyconfig:/config
            - ./Caddyfile:/etc/caddy/Caddyfile
        networks:
            - default
    watchtower:
        image: containrrr/watchtower
        restart: unless-stopped
        networks:
            - default
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /root/.docker/config.json:/config.json
        command: --interval 30 --cleanup --include-restarting --include-stopped
volumes:
    mongodata:

networks:
    default:
        driver: bridge
