version: "3.7"
services:
    fanartweb-mongo:
        image: mongo
        restart: unless-stopped
        container_name: fanartweb-mongo
        volumes:
            - mongodata:/data/db
            - ./backup:/backup
        networks:
            - default
        ports:
            - "127.0.0.1:27017:27017"
        environment:
            - NODE_ENV=production
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=fanartweb
    fanartweb-backend:
        build:
            context: .
            dockerfile: ./packages/backend/Dockerfile
        container_name: fanartweb-backend
        depends_on:
            - fanartweb-mongo
        networks:
            - default
        ports:
            - "127.0.0.1:2162:2162"
        environment:
            - NODE_ENV=production
            - MONGODB_PASS=fanartweb
            - MONGODB_IP=fanartweb-mongo
            - BILI_COOKIE=
volumes:
    mongodata:

networks:
    default:
        driver: bridge
