name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "packages/backend/**"
      - "packages/shared/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "tsconfig.json"
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -f ./packages/backend/Dockerfile -t acedroidx/fanartweb-backend:latest .
      - name: Log In
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        run: docker push acedroidx/fanartweb-backend
