name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - "packages/frontend/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "tsconfig.json"
  workflow_dispatch:

jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    env:
      BASE_API_URL: ${{ secrets.BASE_API_URL }}
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-rc.2
      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
          check-latest: true
          cache: "pnpm"
      # - name: Cache node_modules 📦
      #   uses: actions/cache@v2.1.4
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-
      - name: Install dependencies 👨🏻‍💻
        run: pnpm fetch && pnpm install --offline ; exit 0
      - name: Generate
        run: pnpm run -F fanartweb-frontend generate
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: packages/frontend/dist
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -f ./packages/frontend/Dockerfile -t acedroidx/fanartweb-frontend:latest .
      - name: Log In
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        run: docker push acedroidx/fanartweb-frontend
